package com.github.jonpereiradev.diffobjects;


import com.github.jonpereiradev.diffobjects.strategy.DiffMetadata;

import java.util.List;


/**
 * Contract of the diff config object that maps the properties being check for diff.
 *
 * @author Jonathan Pereira
 * @version 1.2.0
 * @since 1.0.0
 */
public interface DiffConfig {

    /**
     * Build the configuration for the instance.
     *
     * @return the metadata generated by the instance.
     */
    List<DiffMetadata> build();

}
