package com.github.jonpereiradev.diffobjects.builder;


import com.github.jonpereiradev.diffobjects.DiffConfig;

/**
 * Builder responsible for modify the queried field of a class to create a configuration of diff.
 *
 * @author Jonathan Pereira
 * @see DiffConfigBuilderImpl
 * @see DiffConfigBuilder
 * @see DiffConfig
 * @since 1.0.0
 */
public interface DiffQueryFoundBuilder<T> extends DiffQueryBuilder<T> {

    /**
     * Define a property for the last mapping.
     *
     * @param key the identifier of the property.
     * @param value the value of the property.
     *
     * @return the instance of this builder.
     */
    DiffQueryFoundBuilder<T> property(String key, String value);

    /**
     * Removes the mapping that this current query represents.
     *
     * @return the instance of this builder.
     */
    DiffQueryBuilder<T> ignore();

    /**
     * Gets the configuration instance to get the configuration generated by this instance instance.
     *
     * @return a configuration instance instance.
     */
    DiffConfig build();

}
