package com.github.jonpereiradev.diffobjects.builder;

/**
 * Builder with the methods of a instance instance.
 *
 * @author jonpereiradev@gmail.com
 * @see DiffBuilder
 * @see DiffMappingBuilder
 * @see DiffConfiguration
 */
public interface DiffInstanceBuilder {

    /**
     * Gets the mapping instance to registry the fields used in the diff.
     *
     * @return a mapping instance instance.
     */
    DiffMappingBuilder mapper();

    /**
     * Gets the configuration instance to get the configuration generated by this instance instance.
     *
     * @return a configuration instance instance.
     */
    DiffConfiguration configuration();

}

