name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 11

      - name: Test Maven package
        run: mvn -B test --file pom.xml

      - name: Build Maven package
        run: mvn -B package --file pom.xml -DskipTests

      - name: Deploy Sonatype
        run: mvn -P deploy --batch-mode deploy -DskipTests
        env:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
